//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalomobiilisovellus2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lampotila
    {
        public int LampotilaID { get; set; }
        public Nullable<int> TavoiteLampotila { get; set; }
        public Nullable<int> TaloNykyLampotila { get; set; }
        public bool LämmitysON { get; set; }
        public bool LämmitysOFF { get; set; }
    }
}
