//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalomobiilisovellus2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlohuoneValot
    {
        public int ValoID { get; set; }
        public Nullable<bool> ValotPaalla { get; set; }
        public Nullable<bool> Valot0 { get; set; }
        public Nullable<bool> Valot33 { get; set; }
        public Nullable<bool> Valot66 { get; set; }
        public Nullable<bool> Valot100 { get; set; }
    }
}
