//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalomobiilisovellus2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauna
    {
        public int SaunaID { get; set; }
        public string SaunaNro { get; set; }
        public Nullable<int> SaunaNykyLampötila { get; set; }
        public Nullable<int> SaunaTavoiteLampötila { get; set; }
        public bool SaunaPäällä { get; set; }
        public bool SaunaOFF { get; set; }
        public Nullable<System.DateTime> SaunaPäälleTime { get; set; }
        public Nullable<System.DateTime> SaunaOFFTime { get; set; }
    }
}
