//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalomobiilisovellus2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int ValoID { get; set; }
        public bool ValotPaalla { get; set; }
        public bool Valot0 { get; set; }
        public bool Valot33 { get; set; }
        public bool Valot66 { get; set; }
        public bool Valot100 { get; set; }
        public string ValoHuone { get; set; }
        public Nullable<System.DateTime> ValoTime0 { get; set; }
        public Nullable<System.DateTime> ValoTime33 { get; set; }
        public Nullable<System.DateTime> ValoTime66 { get; set; }
        public Nullable<System.DateTime> ValoTime100 { get; set; }
    }
}
